import { test } from "node:test";
import assert from "node:assert/strict";
import { convertLatexToAsciiMath } from "mathlive/ssr";
import { parseEquation } from "../lib/expressions";

// Actual MathLive conversion, including spaces in operator names and the formats
// generated by root, fraction, absolute-value and base-log toolbar templates.
for (const [latex, x, expected] of [
  ["y=ax+b", 3, 7], ["y=-x^2", 3, -9], ["y=2\\sin(x)", Math.PI/2, 2],
  ["y=\\sqrt{x-4}", 8, 2], ["y=\\left|x\\right|", -2, 2],
  ["y=\\sqrt[3]{x}", -8, -2], ["y=\\log_{2}(x)", 8, 3],
  ["y=\\arcsin(x)", 1, Math.PI/2], ["y=\\arccos(x)", 1, 0],
  ["y=\\arctan(x)", 1, Math.PI/4], ["y=\\operatorname{arccsc}(x)", 1, Math.PI/2],
  ["y=\\operatorname{arcsec}(x)", 1, 0], ["y=\\operatorname{arccot}(x)", 1, Math.PI/4],
  ["y=\\csc(x)", Math.PI/2, 1], ["y=\\sec(x)", 0, 1], ["y=\\cot(x)", Math.PI/4, 1],
  ["y=\\frac{ax+b}{2}", 3, 3.5], ["y=x^{\\frac{1}{2}}", 4, 2],
  ["y=\\exp(x)", 1, Math.E], ["y=\\ln(x)", Math.E, 1], ["y=\\log(x)", 100, 2],
] as const) test(`MathLive: ${latex}`, () => {
  const actual = parseEquation(convertLatexToAsciiMath(latex), {a:2,b:1}).evaluate(x);
  assert.ok(Math.abs(actual-expected)<1e-7, `${actual} != ${expected}`);
});
